Fix to allow budget notification email templates > 4Kb (#318)
When configuring email templates > 4kb in tfvars,
terraform apply would fail with:

Error: Error creating Lambda function: InvalidParameterValueException: Lambda was unable to configure your environment variables because the environment variables you have provided exceeded the 4KB limit.

This fix moves the templates to S3 object (instead of env vars) so we are not bound by
the 4kb env var limitation